# DOCKER COMPOSE CONFIGURATION
# This file uses the version 2 docker-compose file format, described here:
# https://docs.docker.com/compose/compose-file/#version-2

version: '2'

services:

  data:
    build: jenkins-data

  master:
    build: jenkins-master
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    volumes_from:
      - data
    ports:
      - "50000:50000"

  nginx:
    build: jenkins-nginx
    ports:
      - "80:80"
    links:
      - master:jenkins-master

  slave:
    build: jenkins-slave
