# DOCKER COMPOSE CONFIGURATION
# This file uses the version 3 docker-compose file format, described here:
# https://docs.docker.com/compose/compose-file/#version-2

version: '2'

services:

  master:
    build: jenkins-master
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data-volume:/var/jenkins_home
      - data-volume:/etc/ansible
    ports:
      - "50000:50000"

  nginx:
    build: jenkins-nginx
    ports:
      - "80:80"
    links:
      - master:jenkins-master

volumes:
  data-volume:
